### ISSUE TITLE
Slow UI changes

### ISSUE THREAD

**Issue by arm61** [easyScience/EasyReflectometryApp#102]
Currently the UI can be slow at times (particularly if there are a lot of models being used). 

This might be due to a few things:
- Slow as XML function being used (@wardsimon has improved this in easyCore so this should be investigated)
- Bad/redundent signalling. 
- Anything else. 

I expect that @rozyczko can help with this.

**Comment by rozyczko** [comment]
Startup and parameter changes seem pretty lean but operations like add/remove model behave BADLY. 
Liberal use of `sampleChanged` along with 7 costly slots for this signal require some restructuring.

**Comment by arm61** [comment]
Yeah I think this comes from lazy GUI programming on my part. Would you like to have a bash at restructuring or do you wanna sit down together want chat about it? (note I am away until like the 10th May).

**Comment by rozyczko** [comment]
I'll try to refactor this signal hell myself a bit. I've done it before with easyDiff so hopefully this won't take much time.

**Comment by rozyczko** [comment]
Branch `performance` has some fixes making model/layer/item manipulation a bit quicker.
I also replaced every expensive dicttoxml calls with the easyCore `XMLSerializer` equivalents.

**Comment by arm61** [comment]
I will try and test tomorrow 👍
