### ISSUE TITLE
Ability to set uniform fit ranges

### ISSUE THREAD

**Issue by acaruana2009** [easyScience/EasyReflectometryApp#33]
The usual setting fit ranges is a minimum here. But samplers these days offer options to use many prior distributions. Having a drop down menu of the most common ones (say Gaussian) when setting a fit range would be really useful.

**Comment by arm61** [comment]
Changing this to be uniform only and opening a separate issue in easyReflectometryLib for the non-uniform priors https://github.com/easyScience/easyReflectometryLib/issues/12

**Comment by arm61** [comment]
This is implemented in the latest develop version as of https://github.com/easyScience/EasyReflectometryApp/commit/b167bbfff64446f197cdb0d7be290514e86bf1ec. So I will close this
