### ISSUE TITLE
CLI application launcher not working after source install - linux

### ISSUE THREAD

**Issue by bmaranville** [easyScience/easyReflectometryApp#39]
After installing with "poetry install" in a Python 3.9.1 virtualenv in linux, the script easyReflectometry fails to run with this error:

```
...
QQmlApplicationEngine failed to load component
file:///home/brian/.virtualenvs/easyReflectometry/bin/Gui/main.qml: No such file or directory
```

The application can be started with python -m easyReflectometryApp.main though (taking what was in the script)

**Comment by AndrewSazonov** [comment]
How did you try to run easyReflectometry after installation, via `poetry run easyReflectometry`?

**Comment by AndrewSazonov** [comment]
BTW, here is the default installation process from the source:

* Install [**Poetry**](https://python-poetry.org/docs/) isolated from the rest of your system (recommended)
  ```
  curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  ```
* Clone **easyReflectometryApp** repo from GitHub
  ```
  git clone https://github.com/easyScience/easyReflectometryApp
  ```
* Go to **easyReflectometryApp** directory
* Create virtual environment for **easyReflectometryApp** and install its dependences using **poetry** 
  ```
  poetry install
  ```  
* Launch **easyReflectometry** application using **poetry**
  ```
  poetry run easyReflectometry
  ```

**Comment by arm61** [comment]
@bmaranville let us know if you had success building from source. Until we have a solution for 18.04 (your comment on #38 might resolve that), installation from source is the best option.

**Comment by arm61** [comment]
@bmaranville just following up to see how things went and if we can help out/close this issue?

**Comment by bmaranville** [comment]
I was able to install from source - thanks.  When a binary installer compatible with 18.04 is available let me know and I will try it out!

**Comment by arm61** [comment]
Awesome! I will close this one now and update you when I find time to play with 18.04 installation.
