### ISSUE TITLE
Continue without a project button - unexpected behaviour

### ISSUE THREAD

**Issue by jfkcooper** [easyScience/EasyReflectometryApp#92]
Windows 10 v.21H2
The `continue without a project` button doesn't appear to do anything. I'm not sure if this is is currently expected or a bug, but I expected it to shift to the next tab or something similar so thought I'd flag it.

**Comment by jfkcooper** [comment]
Okay, having looked at the QML, and retried the button, it does enable the sample and experiment tabs to be accessed, and is expected behaviour (i.e. not a bug)

**Comment by arm61** [comment]
Beat me to it! Yeah expected behaviour. Perhaps there is validity to automatically changing the tab when the button is clicked.

**Comment by jfkcooper** [comment]
I wasn't paying much attention, so clicking it and no major changes made me think it hadn't done something. Probably makes sense anyway to switch tabs as clearly you are done with that tab if you have clicked it, though tis not a big issue

**Comment by arm61** [comment]
I like the idea to change tab automagically so I'll keep this issue open.

**Comment by arm61** [comment]
Unfortunately, I cannot make you a reviewer @jfkcooper but I have opened the following PR to fix this https://github.com/easyScience/EasyReflectometryApp/pull/95

**Comment by arm61** [comment]
Always good to have anyone else look at the code (and I am just trying to trick you into learning QML/starting to contribute)
