### ISSUE TITLE
Can't load data

### ISSUE THREAD

**Issue by jfkcooper** [easyScience/EasyReflectometryApp#94]
Trying to load a .dat file in csv format using the `Import data from local drive` button, nothing appears to happen and no data is loaded. Data looks like:
![image](https://user-images.githubusercontent.com/28106479/193299562-2b3085dc-562d-435e-b699-ea0b834acc9e.png)
[60_61.txt](https://github.com/easyScience/EasyReflectometryApp/files/9685605/60_61.txt)
changed extension to `.txt` to upload here

**Comment by jfkcooper** [comment]
This probably arises from `np.loadtxt` needing `delimiter=","` in  https://github.com/easyScience/EasyReflectometryApp/blob/552edd51d66331eae1fbd939aef91958d3bcb38d/EasyReflectometryApp/Logic/Proxies/Data.py#L195

**Comment by arm61** [comment]
I was about to say this exactly. I would suggest this:
```
else:
    try:
        x, y, ye, xe = np.loadtxt(file_path, unpack=True)
    except ValueError:
        x, y, ye = np.loadtxt(file_path, unpack=True)
        xe = np.zeros_like(ye)
```

becomes something like 

```
else:
    if file_path[-3:] == 'csv':
        try:
            x, y, ye, xe = np.loadtxt(file_path, delimiter=',', unpack=True)
        except ValueError:
            x, y, ye = np.loadtxt(file_path, delimiter=',', unpack=True)
            xe = np.zeros_like(ye)
    else:
        try:
            x, y, ye, xe = np.loadtxt(file_path, unpack=True)
        except ValueError:
            x, y, ye = np.loadtxt(file_path, unpack=True)
            xe = np.zeros_like(ye)
```

Thoughts?

**Comment by jfkcooper** [comment]
Hmm, tricky since I don't think there is a "standard" where comma separated values are definitely called .CSV. Mine were .dat, and I'm sure .txt are also common, but comma and tab separators are both possible in all types (at least in my experience). Could go with insisting, or have more checks (does no throw an error if you assign three variables to a single valued array?)

**Comment by arm61** [comment]
Ideally, we can throw away all of the file reading code and just rely on ORSO... 🙏 

I think the most friendly option will be to have some *rather ugly* checking code. Let me have a look today/tomorrow.

**Comment by arm61** [comment]
@jfkcooper do you fancy having a bash at something that would be friendly for this? (if you are too busy/don't care then I can have a go later in the week)

**Comment by arm61** [comment]
@jfkcooper you happy to close this issue now?
